 version: "3.8"

 services:
  api:
    build:
      dockerfile: dockerfile
      context: "./bff"
    volumes:
      - /app/node_modules
      - ./bff:/app
    ports: 
      - "6000:6000"
    command: "npm start"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: dockerfile
      context: ./login_poc
    volumes:
      - /app/node_modules
      - ./login_poc:/app
    ports: 
      - "3000:3000"
    command: "npm start"
  nginx:
      depends_on:
        - api
        - client
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      ports:
        - "3050:80"